export const dummyData = [
  {
    url: "https://api.github.com/gists/1058268",
    forks_url: "https://api.github.com/gists/1058268/forks",
    commits_url: "https://api.github.com/gists/1058268/commits",
    id: "1",
    node_id: "MDQ6R2lzdDEwNTgyNjg=",
    git_pull_url: "https://gist.github.com/1058268.git",
    git_push_url: "https://gist.github.com/1058268.git",
    html_url: "https://gist.github.com/1058268",
    files: {
      "gistfile1.bash": {
        filename: "gistfile1.bash",
        type: "text/plain",
        language: "Shell",
        raw_url:
          "https://gist.githubusercontent.com/Omer/1058268/raw/48764521110c52033005fa43d7bd6aadfb499e01/gistfile1.bash",
        size: 153,
      },
    },
    public: true,
    created_at: "2011-07-01T10:32:59Z",
    updated_at: "2015-09-26T06:58:07Z",
    description: "prefix bundle exec if Gemfile exists",
    comments: 0,
    user: null,
    comments_url: "https://api.github.com/gists/1058268/comments",
    owner: {
      login: "Omer",
      id: 144857,
      node_id: "MDQ6VXNlcjE0NDg1Nw==",
      avatar_url: "https://avatars.githubusercontent.com/u/144857?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Omer",
      html_url: "https://github.com/Omer",
      followers_url: "https://api.github.com/users/Omer/followers",
      following_url: "https://api.github.com/users/Omer/following{/other_user}",
      gists_url: "https://api.github.com/users/Omer/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Omer/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Omer/subscriptions",
      organizations_url: "https://api.github.com/users/Omer/orgs",
      repos_url: "https://api.github.com/users/Omer/repos",
      events_url: "https://api.github.com/users/Omer/events{/privacy}",
      received_events_url: "https://api.github.com/users/Omer/received_events",
      type: "User",
      site_admin: false,
    },
    truncated: false,
  },
  {
    url: "https://api.github.com/gists/302127",
    forks_url: "https://api.github.com/gists/302127/forks",
    commits_url: "https://api.github.com/gists/302127/commits",
    id: "20",
    node_id: "MDQ6R2lzdDMwMjEyNw==",
    git_pull_url: "https://gist.github.com/302127.git",
    git_push_url: "https://gist.github.com/302127.git",
    html_url: "https://gist.github.com/302127",
    files: {
      "gistfile1.rb": {
        filename: "gistfile1.rb",
        type: "application/x-ruby",
        language: "Ruby",
        raw_url:
          "https://gist.githubusercontent.com/Omer/302127/raw/4c8e2ca2beee09485ca8fef21b83b2777148bf3b/gistfile1.rb",
        size: 195,
      },
    },
    public: true,
    created_at: "2010-02-11T23:37:40Z",
    updated_at: "2015-09-04T09:45:26Z",
    description: null,
    comments: 0,
    user: null,
    comments_url: "https://api.github.com/gists/302127/comments",
    owner: {
      login: "Omer",
      id: 144857,
      node_id: "MDQ6VXNlcjE0NDg1Nw==",
      avatar_url: "https://avatars.githubusercontent.com/u/144857?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Omer",
      html_url: "https://github.com/Omer",
      followers_url: "https://api.github.com/users/Omer/followers",
      following_url: "https://api.github.com/users/Omer/following{/other_user}",
      gists_url: "https://api.github.com/users/Omer/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Omer/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Omer/subscriptions",
      organizations_url: "https://api.github.com/users/Omer/orgs",
      repos_url: "https://api.github.com/users/Omer/repos",
      events_url: "https://api.github.com/users/Omer/events{/privacy}",
      received_events_url: "https://api.github.com/users/Omer/received_events",
      type: "User",
      site_admin: false,
    },
    truncated: false,
  },
  {
    url: "https://api.github.com/gists/302118",
    forks_url: "https://api.github.com/gists/302118/forks",
    commits_url: "https://api.github.com/gists/302118/commits",
    id: "10",
    node_id: "MDQ6R2lzdDMwMjExOA==",
    git_pull_url: "https://gist.github.com/302118.git",
    git_push_url: "https://gist.github.com/302118.git",
    html_url: "https://gist.github.com/302118",
    files: {
      "gistfile1.htm": {
        filename: "gistfile1.htm",
        type: "text/html",
        language: "HTML",
        raw_url:
          "https://gist.githubusercontent.com/Omer/302118/raw/48b385e0fc15b7bdc82d05acb45f04fac6d4969b/gistfile1.htm",
        size: 892,
      },
      "gistfile2.htm": {
        filename: "gistfile2.htm",
        type: "text/html",
        language: "HTML",
        raw_url:
          "https://gist.githubusercontent.com/Omer/302118/raw/45b0fa1401916e9abc496fd9e990b02d4242376d/gistfile2.htm",
        size: 410,
      },
      "gistfile3.htm": {
        filename: "gistfile3.htm",
        type: "text/html",
        language: "HTML",
        raw_url:
          "https://gist.githubusercontent.com/Omer/302118/raw/500bbef0866f8659cb03f22f8a6e0d9520a0eb72/gistfile3.htm",
        size: 311,
      },
    },
    public: true,
    created_at: "2010-02-11T23:33:32Z",
    updated_at: "2015-09-04T09:45:04Z",
    description: null,
    comments: 0,
    user: null,
    comments_url: "https://api.github.com/gists/302118/comments",
    owner: {
      login: "Omer",
      id: 144857,
      node_id: "MDQ6VXNlcjE0NDg1Nw==",
      avatar_url: "https://avatars.githubusercontent.com/u/144857?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Omer",
      html_url: "https://github.com/Omer",
      followers_url: "https://api.github.com/users/Omer/followers",
      following_url: "https://api.github.com/users/Omer/following{/other_user}",
      gists_url: "https://api.github.com/users/Omer/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Omer/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Omer/subscriptions",
      organizations_url: "https://api.github.com/users/Omer/orgs",
      repos_url: "https://api.github.com/users/Omer/repos",
      events_url: "https://api.github.com/users/Omer/events{/privacy}",
      received_events_url: "https://api.github.com/users/Omer/received_events",
      type: "User",
      site_admin: false,
    },
    truncated: false,
  },
  {
    url: "https://api.github.com/gists/302113",
    forks_url: "https://api.github.com/gists/302113/forks",
    commits_url: "https://api.github.com/gists/302113/commits",
    id: "40",
    node_id: "MDQ6R2lzdDMwMjExMw==",
    git_pull_url: "https://gist.github.com/302113.git",
    git_push_url: "https://gist.github.com/302113.git",
    html_url: "https://gist.github.com/302113",
    files: {
      "gistfile1.rb": {
        filename: "gistfile1.rb",
        type: "application/x-ruby",
        language: "Ruby",
        raw_url:
          "https://gist.githubusercontent.com/Omer/302113/raw/a4dd01ccf6e3265eb13ce817c99e9818d4bbfc6c/gistfile1.rb",
        size: 294,
      },
    },
    public: true,
    created_at: "2010-02-11T23:28:09Z",
    updated_at: "2015-09-04T09:45:00Z",
    description: null,
    comments: 0,
    user: null,
    comments_url: "https://api.github.com/gists/302113/comments",
    owner: {
      login: "Omer",
      id: 144857,
      node_id: "MDQ6VXNlcjE0NDg1Nw==",
      avatar_url: "https://avatars.githubusercontent.com/u/144857?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Omer",
      html_url: "https://github.com/Omer",
      followers_url: "https://api.github.com/users/Omer/followers",
      following_url: "https://api.github.com/users/Omer/following{/other_user}",
      gists_url: "https://api.github.com/users/Omer/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Omer/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Omer/subscriptions",
      organizations_url: "https://api.github.com/users/Omer/orgs",
      repos_url: "https://api.github.com/users/Omer/repos",
      events_url: "https://api.github.com/users/Omer/events{/privacy}",
      received_events_url: "https://api.github.com/users/Omer/received_events",
      type: "User",
      site_admin: false,
    },
    truncated: false,
  },
  {
    url: "https://api.github.com/gists/302094",
    forks_url: "https://api.github.com/gists/302094/forks",
    commits_url: "https://api.github.com/gists/302094/commits",
    id: "50",
    node_id: "MDQ6R2lzdDMwMjA5NA==",
    git_pull_url: "https://gist.github.com/302094.git",
    git_push_url: "https://gist.github.com/302094.git",
    html_url: "https://gist.github.com/302094",
    files: {
      "gistfile1.rb": {
        filename: "gistfile1.rb",
        type: "application/x-ruby",
        language: "Ruby",
        raw_url:
          "https://gist.githubusercontent.com/Omer/302094/raw/8a9bd4b35a0f70332764ce850c67b0849f6ab964/gistfile1.rb",
        size: 416,
      },
    },
    public: true,
    created_at: "2010-02-11T23:11:20Z",
    updated_at: "2015-09-04T09:45:04Z",
    description: null,
    comments: 0,
    user: null,
    comments_url: "https://api.github.com/gists/302094/comments",
    owner: {
      login: "Omer",
      id: 144857,
      node_id: "MDQ6VXNlcjE0NDg1Nw==",
      avatar_url: "https://avatars.githubusercontent.com/u/144857?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Omer",
      html_url: "https://github.com/Omer",
      followers_url: "https://api.github.com/users/Omer/followers",
      following_url: "https://api.github.com/users/Omer/following{/other_user}",
      gists_url: "https://api.github.com/users/Omer/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Omer/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Omer/subscriptions",
      organizations_url: "https://api.github.com/users/Omer/orgs",
      repos_url: "https://api.github.com/users/Omer/repos",
      events_url: "https://api.github.com/users/Omer/events{/privacy}",
      received_events_url: "https://api.github.com/users/Omer/received_events",
      type: "User",
      site_admin: false,
    },
    truncated: false,
  },
];
