export const PAGINATION_COUNT = 5;
export const PAGINATION_CONSTANT = {
  PAGE_SIZE: 5,
  PAGE_NUMBER: 1,
};

export const API_STORAGE_KEY = {
  PUBLIC_GISTS_LIST: "PUBLIC_GISTS_LIST",
  FORK_GISTS_LIST: "FORK_GISTS_LIST",
  FORK_USER: "FORK_USER",
};
